packageName = "quic"
version = "0.1.0"
author = "Status Research & Development GmbH"
description = "QUIC protocol implementation"
license = "MIT"

requires "nim >= 1.6.0"
requires "stew#head"
requires "chronos >= 4.0.3 & < 5.0.0"
requires "nimcrypto >= 0.6.0 & < 0.7.0"
requires "ngtcp2 >= 0.35.0"
requires "unittest2"
requires "chronicles >= 0.10.2"
